engines:
  eslint:
    enabled: true
    channel: "eslint-3"
    checks:
    complexity:
      enabled: true

ratings:
   paths:
   - "examples/**/*.js"
   - "lib/*.js"
   - "test/specs/*.js"
   - "*.js"
