language: node_js
node_js:
  - "7"
  - "8"
dist: trusty
sudo: false
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
after_success: npm run coverage
script:
  - npm run ci
